export const QUEUE_EMAIL = 'functions-queue-email'
export const QUEUE_AIRTABLE = 'functions-queue-airtable'
export const QUEUE_STATS = 'functions-queue-stats'
export const QUEUE_DATA = 'functions-queue-data'
export const QUEUE_CLEANUP = 'functions-queue-cleanup'
