export const NONE = 'NONE'
export const BELL1X = 'BELL' // for legacy reasons
export const BELL2X = 'BELL2X'
export const BELL3X = 'BELL3X'
export const DING1X = 'DING' // for legacy reasons
export const DING2X = 'DING2X'
export const DING3X = 'DING3X'
export const BEEP1X = 'BEEP1X'
export const BEEP2X = 'BEEP2X'
export const BEEP3X = 'BEEP' // for legacy reasons
export const BUZZER = 'BUZZER'
export const GONG = 'GONG'
export const WINDCHIME = 'WINDCHIME'
export const SHIPBELL = 'SHIPBELL'
export const SHIPHORN1X = 'SHIPHORNSINGLE'
export const SHIPHORN2X = 'SHIPHORN' // for legacy reasons
export const ITSTIME = 'ITSTIME'
export const SILENCE = 'SILENCE'
